#
#    ░█████╗░██████╗░██╗██████╗░███████╗██████╗░███╗░░░███╗░██████╗
#    ██╔══██╗██╔══██╗██║██╔══██╗██╔════╝██╔══██╗████╗░████║██╔════╝
#    ██║░░╚═╝██████╔╝██║██████╔╝█████╗░░██████╔╝██╔████╔██║╚█████╗░
#    ██║░░██╗██╔══██╗██║██╔═══╝░██╔══╝░░██╔══██╗██║╚██╔╝██║░╚═══██╗
#    ╚█████╔╝██║░░██║██║██║░░░░░███████╗██║░░██║██║░╚═╝░██║██████╔╝
#    ░╚════╝░╚═╝░░╚═╝╚═╝╚═╝░░░░░╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝╚═════╝░
#
#                Автор исходника: swozz
#               Кодер переписавший плагин:CriperMS
#             Благодарю за использование моего плагина!
#                           Плейсхолдеры:
#             %time% = время до перезагрузки
#             Команды: /crestart [Время или stop]
#             Право на использование команды: rwrestart.use
#
#                    Связаться со мной:
#
#                     TG: @agentdoubbl
#

messages:
  bossBarTitle: "&4&lВНИМАНИЕ! &fПерезагрузка сервера через &6&l%time% &fсек."
  restartCountdown: "&6Авто Рестарт &7» &fПерезагрузка сервера через &6%time% &fсек."
  restartTitle: "&4&lВНИМАНИЕ!"
  restartSubtitle: "&fПерезагрузка сервера через &6&l%time% &fсек."
  noPermission: "&6YourServer &7» &fКоманда не найдена"
  countdownStop: "&6Авто Рестарт &7» &fВы остановили перезагрузку!"
  noActiveRestart: "&6Авто Рестарт &7» &fОтсутствуют активные перезагрузки для остановки!"